spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mybatis:
  mapperLocations: classpath:mapper/*.xml
